spring.application.name=lyfe-game-server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URI}
server.address=0.0.0.0
server.port=8080

spring.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:admin@cluster-01.glh3q6b.mongodb.net/lyfe?appName=cluster-01}
mistral.api.key=${MISTRAL_API_KEY:}
cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}
dev.passkey.hash=${DEV_PASSKEY_HASH:}