spring.application.name=lyfe-game-server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://selected-sole-25.clerk.accounts.dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://selected-sole-25.clerk.accounts.dev/.well-known/jwks.json


spring.mongodb.uri=mongodb+srv://lyfe-game-admin:bsSwriKz4vIFumQG@cluster-01.glh3q6b.mongodb.net/?appName=cluster-01
spring.mongodb.database=test