spring.application.name=lyfe-game-server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://selected-sole-25.clerk.accounts.dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://selected-sole-25.clerk.accounts.dev/.well-known/jwks.json
server.address=0.0.0.0
server.port=8080

spring.mongodb.database=test